# Generated by Django 3.2.16 on 2022-10-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='genero',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
