# Generated by Django 3.2.16 on 2022-10-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dpi',
            field=models.CharField(max_length=13, unique=True, verbose_name='Dpi'),
        ),
    ]
